version: '3.8'

services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  evpower-backend:
    build: .
    ports:
      - "9210:9210"  # API и WebSocket порт
    depends_on:
      - redis
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - REDIS_URL=${REDIS_URL}
      - SECRET_KEY=${SECRET_KEY}
      - EZS_SECRET_KEY=${EZS_SECRET_KEY}
      - APP_HOST=${APP_HOST}
      - APP_PORT=${APP_PORT}
      - APP_ENV=${APP_ENV}
      - LOG_LEVEL=${LOG_LEVEL}
      - LOG_PATH=${LOG_PATH}
      - OCPP_WS_PORT=${OCPP_WS_PORT}
      - OCPP_PROTOCOL_VERSION=${OCPP_PROTOCOL_VERSION}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - CORS_ORIGINS=${CORS_ORIGINS}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
      - PAYMENT_PROVIDER=${PAYMENT_PROVIDER}
      - DEFAULT_CURRENCY=${DEFAULT_CURRENCY}
      - PAYMENT_TIMEOUT_MINUTES=${PAYMENT_TIMEOUT_MINUTES}
      - OBANK_API_URL=${OBANK_API_URL}
      - OBANK_POINT_ID=${OBANK_POINT_ID}
      - OBANK_SERVICE_ID=${OBANK_SERVICE_ID}
      - OBANK_USE_PRODUCTION=${OBANK_USE_PRODUCTION}
      - OBANK_CERT_PATH=${OBANK_CERT_PATH}
      - OBANK_CERT_PASSWORD=${OBANK_CERT_PASSWORD}
      - ODENGI_API_URL=${ODENGI_API_URL}
      - ODENGI_MERCHANT_ID=${ODENGI_MERCHANT_ID}
      - ODENGI_PASSWORD=${ODENGI_PASSWORD}
      - ODENGI_WEBHOOK_SECRET=${ODENGI_WEBHOOK_SECRET}
      - ODENGI_USE_PRODUCTION=${ODENGI_USE_PRODUCTION}
      - QR_CODE_LIFETIME_MINUTES=${QR_CODE_LIFETIME_MINUTES}
      - INVOICE_LIFETIME_MINUTES=${INVOICE_LIFETIME_MINUTES}
      - STATUS_CHECK_INTERVAL_SECONDS=${STATUS_CHECK_INTERVAL_SECONDS}
      - CLEANUP_INTERVAL_MINUTES=${CLEANUP_INTERVAL_MINUTES}
      - REDIS_URL=redis://redis:6379
    restart: unless-stopped

volumes:
  redis_data: 