version: '3.8'

services:
  evpower-backend:
    build: .
    container_name: evpower-backend
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.evpower.rule=Host(`ocpp.evpower.kg`)"
      - "traefik.http.routers.evpower.entrypoints=websecure"
      - "traefik.http.routers.evpower.tls=true"
      - "traefik.http.routers.evpower.tls.certresolver=letsencrypt"
      - "traefik.http.services.evpower.loadbalancer.server.port=9210"
      # WebSocket support
      - "traefik.http.middlewares.evpower-headers.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.evpower.middlewares=evpower-headers"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - coolify

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - coolify

volumes:
  redis_data:

networks:
  coolify:
    external: true 