version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: evpower-redis
    restart: unless-stopped
    volumes:
      - redis-data:/data
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - evpower-network

  evpower-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: evpower-backend
    restart: unless-stopped

    environment:
      # Переопределяем критичные переменные для production
      APP_ENV: production
      APP_PORT: 9210
      OCPP_WS_PORT: 9210
      REDIS_URL: redis://redis:6379/0
    ports:
      - "9210:9210"  # API и WebSocket порт
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9210/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - evpower-network
    volumes:
      - ./backend/certificates:/app/certificates:ro
      - /var/log/evpower-ocpp:/var/log/evpower-ocpp
    labels:
      # Метки для Coolify
      - "coolify.managed=true"
      - "coolify.type=compose"
      - "coolify.applicationId=evpower-ocpp"
      - "coolify.serviceId=evpower-backend"

  evpower-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.production
    container_name: evpower-frontend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: https://ocpp.evpower.kg/api
      NEXT_PUBLIC_WS_URL: wss://ocpp.evpower.kg
    ports:
      - "3000:3000"
    depends_on:
      - evpower-backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - evpower-network
    labels:
      # Метки для Coolify
      - "coolify.managed=true"
      - "coolify.type=compose"
      - "coolify.applicationId=evpower-ocpp"
      - "coolify.serviceId=evpower-frontend"

networks:
  evpower-network:
    driver: bridge

volumes:
  redis-data:
    driver: local